### ISSUE TITLE
Delete drops.

### ISSUE THREAD

**Issue by MicahZoltu** [ethercards/tokendrop#4]
https://github.com/ethercards/tokendrop/blob/04874786cda81072f821d1aad02e2fa87a21bc13/contracts/TokenDrop.sol#L112

`delete dropList[idx]` here to cleanup storage and give the user a small gas refund.

**Comment by MicahZoltu** [comment]
I think this should actually be `delete dropList[dropList.length - 1]` and be before the linked line.  I don't _think_ that decreasing the length of the array frees up storage of the last item, though I could be wrong on that.

**Comment by Arachnid** [comment]
Decreasing the array length does cause Solidity to zero out the removed elements. Using `delete dropList[idx]` would zero the element but not reduce the length of the list.

**Comment by MicahZoltu** [comment]
I was aware about delete not shortening the array length, I was unaware that reducing the length would zero out the last element(s).  This will simplify some code of mine, thanks!
